FROM mcr.microsoft.com/devcontainers/base:jammy

# Install packages
RUN apt-get update && apt-get install -y xz-utils make tree curl wget git build-essential gdb llvm clang libelf1 libelf-dev zlib1g-dev libbfd-dev libcap-dev
